name: Deploy the Bot

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push the Docker container
    runs-on: ubuntu-latest
    environment: prod
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: drhayes/derp:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    name: Deploy the Docker container
    runs-on: ubuntu-latest
    needs:
      - build
    environment: prod
    env:
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - name: Find derp-bot host IP
        id: host-ip
        run: |
          DERP_IP=$(curl --silent "https://api.vultr.com/v2/instances?label=derp-bot" -X GET -H "Authorization: Bearer ${VULTR_API_KEY}" | jq --raw-output .instances[0].main_ip)
          echo "::set-output name=derp-ip::$DERP_IP"

      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.DERP_PRIVATE_SSH_KEY }}
          SSH_HOST: ${{ steps.host-ip.outputs.derp-ip }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/derp.key
          chmod 600 ~/.ssh/derp.key
          cat >>~/.ssh/config <<END
          Host derp
            HostName $SSH_HOST
            User root
            IdentityFile ~/.ssh/derp.key
            StrictHostKeyChecking no
          END

      - name: Deploy that bot!
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: bin/deploy.sh

